name: Auto Update Clash Rules

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    - cron: '0 20 * * *' # 每天 UTC 时间 20:00 运行

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run domain rule generation script
        id: generate_domain_rules
        run: python generate_rules.py

      - name: Run GeoIP rule generation script
        id: generate_geoip_rules
        run: python generate_geoip_rules.py

      - name: Commit and push changes
        id: commit_push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          # 检查是否有变动
          if ! git diff --staged --quiet; then
            git commit -m "feat(rules): 自动更新域名和 GeoIP 规则集"
            git push
            echo "changes_pushed=true" >> $GITHUB_OUTPUT
          else
            echo "规则无变化，无需提交。"
            echo "changes_pushed=false" >> $GITHUB_OUTPUT
          fi

      - name: Purge jsDelivr CDN cache
        if: steps.commit_push.outputs.changes_pushed == 'true'
        run: |
          # 获取所有规则目录下有变动的文件列表
          files_to_purge=$(git diff --name-only HEAD~1 HEAD | grep -E '^(clash-rules-generated|geoip-rules-generated)/.*')
          if [ -z "$files_to_purge" ]; then
            echo "没有找到需要刷新的文件。"
            exit 0
          fi
          echo "正在并行刷新以下文件的 CDN 缓存:"
          echo "$files_to_purge"
          
          # 使用 xargs 并发刷新 CDN，-P 50 表示最多50个并行任务
          echo "$files_to_purge" | xargs -I {} -P 50 curl "https://purge.jsdelivr.net/gh/${{ github.repository }}@main/{}"